version: '3.4'
services:

  explorer:
    build:
      context: .
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      - COMPILE_ASSETS=1
    entrypoint: dockerize -wait tcp://explorer_db:5432 -timeout 120s
    depends_on:
      - explorer_db
    command: /app/scripts/start.sh

  explorer_db:
    image: postgres:12
    ports:
      - '5433:5432'
    env_file: .env

  explorer_celery:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://explorer_db:5432 -wait tcp://explorer_redis:6379 -wait tcp://explorer:8000 -timeout 360s
    env_file: .env
    command: /app/scripts/start_celery.sh

  explorer_redis:
    image: redis:3.2
    restart: always
    ports:
      - "6378:6379"

