version: '3.4'
services:

  explorer:
    build:
      context: .
      target: test
    env_file: envs/test.env
    entrypoint: dockerize -wait tcp://explorer_db:5432 -timeout 120s
    depends_on:
      - explorer_db
    command: pytest
    links:
      - "explorer_db"
      - "explorer_celery"
      - "explorer_redis"

  explorer_db:
    image: postgres:12
    ports:
      - "5434:5432"
    env_file: envs/test.env

  explorer_celery:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://explorer_db:5432 -wait tcp://explorer_redis:6379 -wait tcp://explorer:8000 -timeout 360s
    env_file: envs/test.env
    command: /app/scripts/start_celery.sh

  explorer_redis:
    image: redis:3.2
    ports:
      - "6379"
    restart: always
