# Generated by Django 3.0.5 on 2020-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=256)),
                ('dataset', models.CharField(max_length=256)),
                ('slug', models.SlugField(editable=False, max_length=256)),
            ],
            options={
                'unique_together': {('organisation', 'dataset')},
            },
        ),
    ]
